apiVersion: v1
kind: Namespace
metadata:
  name: test-namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-webserver
  namespace: test-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - name: webserver
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: test-webserver-service
  namespace: test-namespace
spec:
  type: NodePort
  selector:
    app: webserver
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30007

