apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: allow-deathstar-for-tiefighters
  namespace: empire
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: deathstar
  ingress:
    - fromEndpoints:
        - matchLabels:
            class: tiefighter
  egress:
    - {}
