apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: restrict-deathstar-access
  namespace: empire
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: deathstar
  ingress:
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: empire
  egress:
    - {}
