apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: allow-deathstar-for-tiefighters
  namespace: empire
spec:
  selector: app.kubernetes.io/name == 'deathstar'
  order: 500
  ingress:
    - action: Allow
      source:
        selector: class == 'tiefighter'
  egress:
    - action: Allow
